inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Layout/ArgumentAlignment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/MultilineArrayLineBreaks:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - ca
    - id
    - sg
    - tf

Rake/MethodDefinitionInTask:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/EachWithObject:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
