# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@8bc9ca9ace0139aae24423f15269b9673354b495
      with:
        ruby-version: 2.7.1

    - name: Install dependencies
      run: bundle install

    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.16.3

    - name: Install node deps
      run: |
        npm install -g yarn
        yarn install
        sudo apt-get install libsqlite3-dev

    - name: Run tests
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
        bundle exec rails test
        bundle exec rubocop

        bundle exec rake assets:precompile

    - name: Lint
      run: bundle exec rubocop
